# Generated by Django 4.1.7 on 2023-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='회원이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='회원상태')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자여부')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
