# Generated by Django 4.1.7 on 2023-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 사용중인 이메일입니다'}, max_length=254, unique=True, verbose_name='이메일'),
        ),
    ]
