# Generated by Django 4.1.7 on 2023-04-02 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('선택', None), ('SHOP', '쇼핑'), ('EAT', '식비'), ('FIX', '고정비'), ('ACT', '여가활동비'), ('EDU', '교육비'), ('ECT', '기타')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
